# Configuration about the monitored REST server
monitored:
  # The URL base to the monitored server
  url.base: http://localhost:8090

  # The number of time the execution is repeated
  demo.repetitions: 100

  # The configuration to load the exposed JMX Mbeans of the monitored application
  jmx:
    rmi:
      host: localhost
      port: 1099
      endpoint: jmxrmi

# Monitoring configuration
monitoring:
  interval:
    length: 200
    unit: ms
