language: java

addons:
  sonarqube:
    organization: bdm-lu
    token: $SONARQUBE_TOKEN
    branches:
      - master

jdk:
  - oraclejdk8

cache:
  directories:
    - powerapi-demo-monitor-proxy/node
    - powerapi-demo-monitor-proxy/node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache

env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
