# The port the service is exposed on
server.port: 8090

# Sample data
sample:
  maxAge: 100
  size: 10000000

# The RMI expose configuration
jmx.rmi:
  host: localhost
  port: 1099
  endpoint: jmxrmi
