omdb:
  url: http://www.omdbapi.com/

# The RMI expose configuration
jmx.rmi:
  host: localhost
  port: 1099
  endpoint: jmxrmi

# The MongoDB access configuration
spring.data.mongodb:
  database: pcol-mongo-db
  uri: mongodb://127.0.0.1:27017
